{% set name = "weasel" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aabc210f072e13f6744e5c3a28037f93702433405cd35673f7c6279147085aa9

build:
  entry_points:
    - weasel = weasel.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - confection >=0.0.4,<0.2.0
    - packaging >=20.0
    - wasabi >=0.9.1,<1.2.0
    - srsly >=2.4.3,<3.0.0
    - typer >=0.3.0,<1.0.0
    - cloudpathlib >=0.7.0,<1.0.0
    - smart-open >=5.2.1,<8.0.0
    - requests >=2.13.0,<3.0.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0

test:
  imports:
    - {{ name }}
  requires:
    - pytest >=5.2.0,!=7.1.0
    - pip
    - git
    - requests
    - python {{ python_min }}
  commands:
    - pip check
    - weasel --help
    - python -m pytest --tb=native --pyargs {{ name }}


about:
  home: https://github.com/explosion/weasel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small and easy workflow system
  description: |
    Weasel lets you manage and share end-to-end workflows for different use
    cases and domains, and orchestrate training, packaging and serving your
    custom pipelines.
  doc_url: https://github.com/explosion/weasel
  dev_url: https://github.com/explosion/weasel

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/spacy
